import type { Lesson } from './types';

/** Appended to the provider/provenance when YouTube's speech recognition made the captions. */
export const AUTO_GENERATED_SUFFIX = ' (auto-generated)';
export const autoGeneratedCaptions = (provenance: string | undefined) =>
  !!provenance?.endsWith(AUTO_GENERATED_SUFFIX);

/** Learner-facing description of where a lesson's Japanese came from. */
export function transcriptLabel(lesson: Lesson) {
  if (lesson.source === 'demo') return 'Studio sample · Japanese synthetic voice';
  const provenance = lesson.transcript?.provenance ?? lesson.transcriptSource ?? '';
  if (autoGeneratedCaptions(provenance))
    return 'YouTube auto-generated captions · punctuation and timing may be rough';
  switch (lesson.transcript?.type) {
    case 'provider-captions':
      return lesson.source === 'page' ? 'Subtitles from the page' : 'YouTube captions';
    case 'generated':
      return 'AI subtitles';
    case 'user-upload':
    case 'user-paste':
      return 'Your subtitles';
    default:
      return provenance;
  }
}

/**
 * For YouTube lessons built on auto-generated captions: the Home import route that regenerates
 * the subtitles with Whisper from the learner's own copy of the audio.
 */
export function whisperUpgradePath(lesson: Lesson) {
  const provenance = lesson.transcript?.provenance ?? lesson.transcriptSource ?? '';
  if (lesson.source !== 'youtube' || !lesson.videoId || !autoGeneratedCaptions(provenance))
    return null;
  const video = `https://www.youtube.com/watch?v=${lesson.videoId}`;
  return `/?video=${encodeURIComponent(video)}&subtitles=generate`;
}
