// Review generated SQL before committing. Never run generated migrations directly in production.
import { DatabaseSync } from 'node:sqlite';
import { getMigrations } from 'better-auth/db/migration';
import { writeFile } from 'node:fs/promises';
import { createAuth } from '../src/lib/auth/server';
const auth = createAuth(new DatabaseSync(':memory:'), {
  AUTH_SECRET: 'migration-only-placeholder-32-characters',
  AUTH_BASE_URL: 'http://localhost:3000',
});
const plan = await getMigrations(auth.options);
await writeFile(
  'migrations/0002_auth.sql',
  '-- Generated by Better Auth 1.7.7, additive SQLite/D1 schema.\n' +
    (await plan.compileMigrations()),
);
console.log('Generated auth tables:', plan.toBeCreated.map((t) => t.table).join(', '));
